networks:
  dev:
    driver: bridge

volumes:
  gallery_storage:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - gallery_storage:/storage
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    environment:
      - API_HOST=backend
      - API_PORT=8000
      - PYTHONUNBUFFERED=1
    ports:
      - "3000:3000"
    volumes:
      - gallery_storage:/frontend/storage
    networks:
      - dev

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - gallery_storage:/backend/storage
    networks:
      - dev
